environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    freetype_version: "2-10-2"
  matrix:
  - library: static
  # library: shared
  
platform:
  - x86
  - amd64
  
configuration:
  - release
  - debug

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Submodules
  - git submodule init
  - git submodule update
  # Get freetype2 source from GIT
  - ps: ./load-freetype.ps1 $env:freetype_version
  # Load libraries (zlib, libpng)
  - ps: ./EZTools/load-library.ps1 "Zlib1"   $env:platform $env:configuration
  - ps: ./EZTools/load-library.ps1 "libpng" $env:platform $env:configuration
  
build_script:
  - ps: ./build.ps1 $env:platform $env:configuration

after_build:
  - ps: ./rename.ps1 $env:freetype_version $env:platform $env:configuration
  
test: off

artifacts:
 - path: 'freetype/build/freetype2-%platform%-%configuration%.zip'

deploy:
- provider: GitHub
# I am tagging through github
# Tag format is v<major version>.<minor version>, shall be consistent with major.monir of Appveyor build
# release: v$(appveyor_build_version)
  description: 'freetype2 appveyor build script [$(appveyor_build_version)] with binaries'
  auth_token:
    secure: 7fz/vsEpOOUyPYNmrykrY4lgqu3XQsag6g4x25nOwtd2dM2kc3X3GPoPzMCMDno/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
