environment:
  global:
    ZLIB_at_GIT: "https://github.com/madler/zlib"

platform:
  - x86
  - x64

install:
  # Get zlib source from GIT
  - mkdir zlib
 
build_script:                                                                                   
  # Build
   - echo Hi

on_success:
  # "for /f %%f in ('conda build -q --output .') do anaconda -t %ANACONDA_TOKEN% upload -u maxirmx --force --no-progress %%f"
