environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    freetype_version: "2-10-1"
  matrix:
  - library: static
  # library: shared
  
platform:
  # x86
  - amd64
  
configuration:
  # release
  - debug

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get freetype2 source from GIT
  - appveyor DownloadFile http://git.savannah.gnu.org/cgit/freetype/freetype2.git/snapshot/freetype2-VER-%freetype_version%.tar.gz
  - 7z x freetype2-VER-%freetype_version%.tar.gz
  - 7z x freetype2-VER-%freetype_version%.tar
  - ren freetype2-VER-%freetype_version% freetype
  - ps: './load-libraries.ps1 %platform%'
  
build_script:
  - cd freetype
  - dir
  - mkdir build
  - cmake  -E chdir build cmake -G "NMake Makefiles" ..
  - cmake --build build  
  
test: off

#artifacts:
   # path: zlib\zlib.lib
   # path: zlib\zlib1.dll
   # path: zlib\zdll.lib
   # path: zlib\zlib.h

