environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    
platform:
  # x86
  - amd64

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get podofo source from Source Forge  (-L option is required to follow redirects)
  - curl -L  https://sourceforge.net/projects/podofo/files/podofo/0.9.6/podofo-0.9.6.tar.gz > podofo-0.9.6.tar.gz
  - 7z x podofo-0.9.6.tar.gz
  - 7z x podofo-0.9.6.tar
  # Get zlib  
  - mkdir zlib
  - cd zlib
  - curl -L http://www.samsonov.net/wp?kcccount=http://www.samsonov.net/wp/assets/Dist_zlib/X64-release/zlib.7z > zlib.7z
  - 7z x zlib.7z
  - dir
  - cd ..   
build_script:
  - SET
  - SET INCLUDE= %APPVEYOR_BUILD_FOLDER%\zlib\include;%INCLUDE%
  - SET PATH= %APPVEYOR_BUILD_FOLDER%\zlib\lib;%PATH%
  - SET
  - cd podofo-0.9.6
  - mkdir build
  - cd build
  - cmake .. 
  
test: off

#artifacts:
   # path: zlib\zlib.lib
   # path: zlib\zlib1.dll
   # path: zlib\zdll.lib
   # path: zlib\zlib.h

