environment:
  global:
    ZLIB_at_GIT: "https://github.com/madler/zlib"

platform:
  - x86
  - x64

install:
  # Get zlib source from GIT
  - git clone -q --branch=master %ZLIB_at_GIT% zlib
   
build_script:                                                                                   
  # Build
   - nmake -f win32/Makefile.msc LOC="-DASMV -DASMINF" OBJA="inffas32.obj match686.obj"  

on_success:
  # "for /f %%f in ('conda build -q --output .') do anaconda -t %ANACONDA_TOKEN% upload -u maxirmx --force --no-progress %%f"
