environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    freetype_version: "2-10-2"
  matrix:
  - library: static
  # library: shared
  
platform:
  - x86
  - amd64
  
configuration:
  # release
  - debug

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get freetype2 source from GIT
  - ps: ./load-freetype.ps1 $env:freetype_version
  # Load libraries (zlib, libpng)
  - ps: ./load-libraries.ps1 $env:platform $env:configuration
  
build_script:
  - ps: ./build.ps1 $env:platform 
  
test: off

#artifacts:
   # path: zlib\zlib.lib
   # path: zlib\zlib1.dll
   # path: zlib\zdll.lib
   # path: zlib\zlib.h

