environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'

platform:
  - x86
  # amd64

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get libpng source from GIT
  - appveyor DownloadFile http://download.savannah.gnu.org/releases/freetype/freetype-2.7.tar.gz
  - 7z x freetype-2.7.tar.gz
  - 7z x freetype-2.7.tar
   
build_script:                                                                                   
  # Build
  - cd freetype-2.7
  - C:\MinGW\bin\mingw32-make -f builds\windows\w32-vcc.mk
  
test: off

#artifacts:
   # path: zlib\zlib.lib
   # path: zlib\zlib1.dll
   # path: zlib\zdll.lib
   # path: zlib\zlib.h

