environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    freetype_version: "2-10-2"
  matrix:
  - library: static
  # library: shared
  
platform:
  - x86
  - amd64
  
configuration:
  - release
  - debug

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get freetype2 source from GIT
  - ps: ./load-freetype.ps1 '%freetype_version%'
  # Load libraries (zlib, libpng)
  - ps: ./load-library.ps1 "ZLib"   %platform% %configuration%
  - ps: ./load-library.ps1 "libpng" %platform% %configuration%
  
build_script:
  - ps: ./build.ps1 %platform% %configuration%

after_build:
  - ps: ./rename.ps1 %freetype_version% %platform% %configuration%
  
test: off

artifacts:
 - path: "freetype/build/freetype-%platform%-%configuration%.zip"

deploy:
- provider: GitHub
  release: $(appveyor_build_version)
  description: 'freetype2 build [$(appveyor_build_version)]'
  auth_token:
    secure: 7fz/vsEpOOUyPYNmrykrY4lgqu3XQsag6g4x25nOwtd2dM2kc3X3GPoPzMCMDno/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: false       # deploy on tag push only
